services:
  keycloak:
    image: 52north/keycloak:latest
    container_name: keycloak
    restart: on-failure:5
#    network_mode: host
    ports:
      - 8080:8080
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json
      - ./data:/opt/keycloak/data/h2/
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=http://kommonitor/keycloak
      - KC_PROXY_HEADERS=xforwarded
  keycloak-proxy:
    image: nginx:latest
    container_name: keycloak-proxy
    restart: unless-stopped
#    network_mode: host
    ports:
      - 80:80
    depends_on:
      - keycloak
    volumes:
      - ./keycloak.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - NGINX_PORT=80
      - KEYCLOAK=keycloak:8080