services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    restart: on-failure:5
    ports:
      - 8080:8080
      - 8787:8787
    command:
      - start-dev
      - --import-realm
      - --features=scripts
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json
      - ../target/keycloak-ip-authenticator-0.0.1-SNAPSHOT-jar-with-dependencies.jar:/opt/keycloak/providers/keycloak-ip-authenticator-0.0.1-SNAPSHOT.jar
      - ./data:/opt/keycloak/data/h2/
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
      - DEBUG=true
      - DEBUG_PORT='*:8787'
      - KC_LOG_LEVEL=info,org.n52:debug
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=http://kommonitor/keycloak
      - KC_PROXY_HEADERS=xforwarded
  kommonitor-proxy:
    image: nginx:latest
    container_name: kommonitor-proxy
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - keycloak
    volumes:
      - ./keycloak.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - NGINX_PORT=80
      - KEYCLOAK=keycloak:8080